export const categories = ["Airy Earthy Aquatic Extreme",
"Airy Tobacco Aromatic Intense",
"Airy Woody Citrus Noir",
"Airy Woody Gourmand Extreme",
"Bold Amber Tobacco Noir",
"Bold Earthy Citrus Intense",
"Bold Fougère Leather Intense",
"Bold Fougère Ozonic Extreme",
"Bold Green Musky Light",
"Bold Spicy Fougère",
"Bold Woody Earthy Intense",
"Brisk Amber Floral Noir",
"Brisk Aromatic Woody Extreme",
"Brisk Balsamic Aquatic Extreme",
"Brisk Citrus Aromatic Light",
"Brisk Fruity Woody Noir",
"Brisk Gourmand Citrus Noir",
"Brisk Leather Aromatic Light",
"Brisk Leather Citrus Intense",
"Brisk Spicy Aquatic Extreme",
"Classic Aquatic Fougère Light",
"Classic Aromatic Leather Intense",
"Classic Balsamic Aquatic",
"Classic Musky Aquatic Intense",
"Classic Ozonic Gourmand Noir",
"Classic Spicy Ozonic Noir",
"Classic Woody Ozonic",
"Clean Citrus Leather Light",
"Clean Oriental Ozonic Noir",
"Clean Oriental Tobacco",
"Clean Spicy Fougère Intense",
"Clean Spicy Ozonic Light",
"Cold Aquatic Gourmand Noir",
"Cold Aromatic Tobacco Noir",
"Cold Earthy Tobacco Extreme",
"Cold Floral Fougère Extreme",
"Cold Gourmand Balsamic Extreme",
"Cold Ozonic Fruity Noir",
"Cold Spicy Fruity Noir",
"Cold Woody Citrus Intense",
"Creamy Fruity Woody Noir",
"Creamy Gourmand Green",
"Creamy Green Fougère Intense",
"Creamy Leather Tobacco Extreme",
"Creamy Woody Earthy Light",
"Dark Musky Fruity Noir",
"Dark Spicy Tobacco Extreme",
"Deep Earthy Balsamic Extreme",
"Deep Fougère Oriental",
"Deep Tobacco Spicy Intense",
"Deep Woody Aquatic Extreme",
"Deep Woody Leather Intense",
"Deep Woody Oriental Light",
"Delicate Aromatic Musky Extreme",
"Delicate Balsamic Fruity Extreme",
"Delicate Ozonic Amber Noir",
"Dirty Amber Spicy Extreme",
"Dirty Citrus Amber Noir",
"Dirty Earthy Musky Extreme",
"Dirty Floral Spicy Noir",
"Dirty Fruity Tobacco",
"Dirty Spicy Amber Light",
"Dry Aquatic Floral Extreme",
"Dry Aromatic Amber Light",
"Dry Earthy Fruity",
"Dry Gourmand Tobacco",
"Dry Leather Spicy Intense",
"Dry Oriental Fruity Noir",
"Dry Ozonic Fougère",
"Fresh Citrus Leather Extreme",
"Fresh Earthy Aromatic",
"Fresh Earthy Fougère Intense",
"Fresh Floral Aromatic",
"Fresh Gourmand Tobacco Noir",
"Fresh Green Aquatic",
"Fresh Ozonic Balsamic Intense",
"Fresh Woody Floral Light",
"Fresh Woody Oriental Intense",
"Green Citrus Tobacco Light",
"Green Leather Fougère",
"Green Leather Gourmand Noir",
"Icy Aquatic Leather Light",
"Icy Gourmand Earthy Extreme",
"Icy Green Aromatic Light",
"Icy Green Ozonic Extreme",
"Icy Woody Spicy",
"Incensey Aquatic Green Extreme",
"Incensey Aromatic Citrus Noir",
"Incensey Citrus Earthy Intense",
"Incensey Floral Balsamic Noir",
"Incensey Gourmand Fougère Noir",
"Incensey Leather Earthy Intense",
"Incensey Spicy Floral Light",
"Incensey Woody Aromatic",
"Intense Citrus Fougère Noir",
"Intense Floral Woody Noir",
"Intense Fougère Musky Extreme",
"Intense Fougère Spicy Extreme",
"Intense Fruity Gourmand Extreme",
"Intense Green Aromatic Extreme",
"Intense Woody Fougère Noir",
"Juicy Amber Fruity Extreme",
"Juicy Earthy Musky Extreme",
"Juicy Earthy Spicy Light",
"Juicy Oriental Tobacco Light",
"Juicy Ozonic Tobacco Noir",
"Juicy Spicy Leather Light",
"Leathery Earthy Citrus Light",
"Leathery Floral Fruity Extreme",
"Leathery Gourmand Fruity Light",
"Leathery Leather Gourmand Noir",
"Leathery Tobacco Spicy Intense",
"Leathery Woody Earthy Light",
"Leathery Woody Oriental Noir",
"Light Gourmand Tobacco Extreme",
"Light Green Earthy Intense",
"Light Leather Floral Light",
"Light Oriental Earthy Noir",
"Metallic Citrus Leather Intense",
"Metallic Citrus Woody Extreme",
"Metallic Fruity Green Intense",
"Metallic Leather Oriental Extreme",
"Metallic Spicy Green Intense",
"Modern Balsamic Tobacco Light",
"Modern Earthy Spicy Light",
"Modern Ozonic Oriental Noir",
"Modern Spicy Woody Noir",
"Modern Tobacco Floral Intense",
"Modern Tobacco Woody Extreme",
"Powdery Citrus Leather",
"Powdery Floral Amber Extreme",
"Powdery Green Gourmand Light",
"Powdery Musky Aromatic Extreme",
"Powdery Musky Spicy Intense",
"Powdery Oriental Floral Extreme",
"Powdery Spicy Tobacco",
"Powdery Woody Floral Extreme",
"Powdery Woody Gourmand Noir",
"Resinous Aromatic Citrus Light",
"Resinous Fruity Balsamic Light",
"Resinous Gourmand Citrus Intense",
"Resinous Musky Fougère Light",
"Resinous Ozonic Floral Intense",
"Rustic Citrus Balsamic Light",
"Rustic Fougère Gourmand Light",
"Rustic Green Fougère Noir",
"Rustic Ozonic Leather Noir",
"Rustic Tobacco Earthy Noir",
"Rustic Woody Green Extreme",
"Sharp Aquatic Aromatic Intense",
"Sharp Aquatic Fruity Light",
"Sharp Gourmand Fruity Noir",
"Sharp Leather Green Light",
"Smoky Aromatic Earthy Intense",
"Smoky Fruity Tobacco Intense",
"Smoky Gourmand Earthy Intense",
"Smoky Musky Citrus Intense",
"Smoky Musky Fougère",
"Smoky Spicy Aromatic Noir",
"Smoky Tobacco Green Noir",
"Soapy Fougère Balsamic Noir",
"Soapy Fougère Oriental Noir",
"Soapy Gourmand Aquatic Extreme",
"Soapy Gourmand Fruity",
"Soapy Spicy Aquatic Noir",
"Soft Aquatic Balsamic Noir",
"Soft Aromatic Amber",
"Soft Balsamic Floral Extreme",
"Soft Floral Balsamic Intense",
"Soft Gourmand Leather Light",
"Soft Gourmand Tobacco Light",
"Soft Green Aromatic Intense",
"Soft Oriental Floral Intense",
"Soft Ozonic Musky Intense",
"Soft Spicy Earthy Light",
"Soft Spicy Green Intense",
"Sweet Amber Woody",
"Sweet Aquatic Floral Intense",
"Sweet Aromatic Earthy Extreme",
"Sweet Balsamic Ozonic Noir",
"Sweet Fougère Fruity Noir",
"Sweet Fruity Balsamic Light",
"Sweet Gourmand Citrus Light",
"Sweet Leather Musky Noir",
"Warm Aquatic Fruity Light",
"Warm Aquatic Green Light",
"Warm Citrus Balsamic Intense",
"Warm Citrus Woody Extreme",
"Warm Green Amber Noir",
"Warm Musky Gourmand",
"Warm Oriental Tobacco Light",
"Warm Tobacco Oriental Noir",
"Zesty Aromatic Oriental Intense",
"Zesty Citrus Earthy",
"Zesty Earthy Aromatic Intense",
"Zesty Fruity Tobacco Light",
"Zesty Gourmand Spicy Light",
"Zesty Gourmand Tobacco Intense",
"Zesty Woody Aromatic Light",
"Zesty Woody Musky",]